name: Deploy todos backend
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "todos-backend/**"
      - ".github/workflows/backend.yml"
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add backend remote origin
        run: git remote add heroku-backend https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      - name: Deploy backend to Heroku
        run: git push heroku-backend `git subtree split --prefix todos-backend main`:refs/heads/main --force
