name: Deploy todos frontend
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "todos-frontend/**"
      - ".github/workflows/frontend.yml"
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add frontend remote origin
        run: git remote add heroku-frontend https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME }}.git
      - name: Deploy frontend to Heroku
        run: git push heroku-frontend `git subtree split --prefix todos-frontend main`:refs/heads/main --force
